  
insert into packs 
    (name, contributor)
values
 ('kc-masterpiece', 'casey'),
 ('trunk-shakin', 'nedim');
    
insert into sounds
    (name, url, tag)
values
    -- Need to reference pack by id
  ('auto1', 'Auto 001 Cm7.wav', 'juice'),
    ('auto2', 'Auto 002 A#m7.wav', 'juice'),
  ('auto3', 'Auto 003 CMaj7.wav', 'juice'),
  ('auto4', 'Auto 004 A#Maj7.wav', 'juice'),
  ('butterflies1', 'Butterflies 001 GMaj9.wav', 'juice'),
  ('butterflies2', 'Butterflies 002 C#Maj9.wav', 'juice'),
  ('chardonnay1', 'Chardonnay 001 D#Maj7.wav', 'juice'),
  ('chardonnay2', 'Chardonnay 002 C#Maj7.wav', 'juice'),
  ('chardonnay3', 'Chardonnay 003 CMaj7.wav', 'juice'),
  ('chardonnay4', 'Chardonnay 004 AMaj7.wav', 'juice'),
  ('chardonnay5', 'Chardonnay 005 G#Maj7.wav', 'juice'),
  ('chardonnay6', 'Chardonnay 006 D#Maj7.wav', 'juice'),
  ('cherry1', 'Cherry 001 A#min9.wavv', 'juice'),
  ('cherry2', 'Cherry 002 G#min9.wav', 'juice'),
  ('cherry3', 'Cherry 003 Gmin9.wav', 'juice'),
  ('cherry4', 'Cherry 004 D#min9.wav', 'juice'),
  ('cherry5', 'Cherry 005 Cmin9.wav', 'juice'),
  ('cherry6', 'Cherry 006 A#min9.wav', 'juice'),
  ('cloudy1', 'Cloudy 001 Fm7.wav', 'juice'),
  ('cloudy2', 'Cloudy 002 FMaj7.wav', 'juice'),
  ('cloudy3', 'Cloudy 003 Em7.wav', 'juice'),
  ('cloudy4', 'Cloudy 004 EMaj7.wav', 'juice'),
  ('cloudy5', 'Cloudy 005 D#m7.wav', 'juice'),
  ('cloudy6', 'Cloudy 006 D#Maj7.wav', 'juice'),
  ('cloudy7', 'Cloudy 007 Dm7.wav', 'juice'),
  ('cloudy8', 'Cloudy 008 DMaj7.wav', 'juice'),
  ('mobfx1', 'Cymatics - 808 Mob FX 1 - Alarm.wav', 'juice'),
  ('mobfx2', 'Cymatics - 808 Mob FX 1 - Telephone In Wonderland.wav', 'juice'),
  ('mobfx3', 'Cymatics - 808 Mob FX 2 - Synth Riser.wav', 'juice'),
  ('mobfx4', 'Cymatics - 808 Mob FX 3 - Radio Chunk Hit.wav', 'juice'),
  ('mobfx5', 'Cymatics - 808 Mob FX 4 - Alarm On Acid.wav', 'juice'),
  ('mobfx6', 'Cymatics - 808 Mob FX 5 - Tight Rewind.wav', 'juice'),
  ('mobfx7', 'Cymatics - 808 Mob FX 6 - Deep Glass.wav', 'juice'),
  ('mobfx8', 'Cymatics - 808 Mob FX 7 - Fire Alarm.wav', 'juice'),
  ('mobfx9', 'Cymatics - 808 Mob FX 8 - Vital Signs.wav', 'juice'),
  ('mobfx10', 'Cymatics - 808 Mob FX 9 - Change Station.wav', 'juice'),
  ('mobfx11', 'Cymatics - 808 Mob FX 10 - Disconnected.wav', 'juice'),
  ('mobfx12', 'Cymatics - 808 Mob FX 11 - Kill Bill Siren.wav', 'juice'),
  ('mobfx13', 'Cymatics - 808 Mob FX 12 - Kill Bill Siren 2.wav', 'juice'),
  ('mobfx14', 'Cymatics - 808 Mob FX 13 - Stadium Rodeo.wav', 'juice'),
  ('mobperc2', 'Cymatics - 808 Mob Percussion 1.wav', 'juice'),
  ('mobperc3', 'Cymatics - 808 Mob Percussion 2.wav', 'juice'),
  ('mobperc4', 'Cymatics - 808 Mob Percussion 3.wav', 'juice'),
  ('mobperc5', 'Cymatics - 808 Mob Percussion 4.wav', 'juice'),
  ('mobperc6', 'Cymatics - 808 Mob Percussion 5.wav', 'juice'),
  ('mobperc7', 'Cymatics - 808 Mob Percussion 6.wav', 'juice'),
  ('mobperc8', 'Cymatics - 808 Mob Percussion 7.wav', 'juice'),
  ('mobperc9', 'Cymatics - 808 Mob Percussion 8.wav', 'juice'),
  ('mobperc10', 'Cymatics - 808 Mob Percussion 9.wav', 'juice'),
  ('mobperc11', 'Cymatics - 808 Mob Percussion 10.wav', 'juice'),
  ('mobperc12', 'Cymatics - 808 Mob Percussion 11.wav', 'juice'),
  ('mobperc13', 'Cymatics - 808 Mob Percussion 12.wav', 'juice'),
  ('futurebassvocal150bpm', 'Cymatics - Future Bass Vocal Loop 2 - 150 BPM F Min.wav', 'juice'),
  ('futurebassvocal160bpm', 'Cymatics - Future Bass Vocal Loop 3 - 160 BPM F# Min.wav', 'juice'),
  ('futurebassvocal140bpm', 'Cymatics - Future Bass Vocoder Loop 2 - 140 BPM F Min.wav', 'juice'),
  ('hybridtrap8081', 'Cymatics - Hybrid Trap 808 1 - C#.wav', 'juice'),
  ('hybridtrap8082', 'Cymatics - Hybrid Trap 808 2 - D.wav', 'juice'),
  ('hybridtrap8083', 'Cymatics - Hybrid Trap 808 3 - D.wav', 'juice'),
  ('hybridtrap8084', 'Cymatics - Hybrid Trap 808 4 - D.wav', 'juice'),
  ('hybridtrap8085', 'Cymatics - Hybrid Trap 808 5 - E.wav', 'juice'),
  ('hybridtrap8086', 'Cymatics - Hybrid Trap 808 6 - E.wav', 'juice'),
  ('hybridtrap8087', 'Cymatics - Hybrid Trap 808 7 - E.wav', 'juice'),
  ('hybridtrap8088', 'Cymatics - Hybrid Trap 808 8 - F.wav', 'juice'),
  ('hybridtrap8089', 'Cymatics - Hybrid Trap 808 9 - F.wav', 'juice'),
  ('hybridtrap80810', 'Cymatics - Hybrid Trap 808 10 - G#.wav', 'juice'),
  ('lofimel100bpm', 'Cymatics - Lofi Melody Loop 11 - 100 BPM D Maj.wav', 'juice'),
  ('mothershipbass1', 'Cymatics - Mothership Bass One Shot 1 - E.wav', 'juice'),
  ('mothershipbass2', 'Cymatics - Mothership Bass One Shot 2 - E.wav', 'juice'),
  ('mothershipbass3', 'Cymatics - Mothership Bass One Shot 3 - E.wav', 'juice'),
  ('mothershipbass4', 'Cymatics - Mothership Bass One Shot 4 - E.wav', 'juice'),
  ('mothershipbass5', 'Cymatics - Mothership Bass One Shot 5 - F.wav', 'juice'),
  ('mothershipbass6', 'Cymatics - Mothership Bass One Shot 6 - F.wav', 'juice'),
  ('mothershipbass7', 'Cymatics - Mothership Bass One Shot 7 - F.wav', 'juice'),
  ('mothershipbass8', 'Cymatics - Mothership Bass One Shot 8 - F.wav', 'juice'),
  ('mothershipbass9', 'Cymatics - Mothership Bass One Shot 9 - F.wav', 'juice'),
  ('mothershipbass10', 'Cymatics - Mothership Bass One Shot 10 - F.wav', 'juice'),
  ('mothershipbass11', 'Cymatics - Mothership Bass One Shot 11 - F.wav', 'juice'),
      ('mothershipbass12', 'Cymatics - Mothership Bass One Shot 12 - F#.wav', 'juice'),
  ('mothershipbass13', 'Cymatics - Mothership Bass One Shot 13 - F#.wav', 'juice'),
  ('mothershipbass14', 'Cymatics - Mothership Bass One Shot 14 - G#.wav', 'juice'),
  ('promethiusvococ140bpm', 'Cymatics - Prometheus Vocoder Loop 26 - 140 BPM G Min.wav', 'juice'),
  ('promethiusvococ174bpm', 'Cymatics - Prometheus Vocoder Loop 47 - 174 BPM A# Min.wav', 'juice'),
  ('cymanticssnare1', 'Cymatics - Snare 1.wav', 'sauce'),
  ('cymanticssnare2', 'Cymatics - Snare 2.wav', 'sauce'),
  ('cymanticssnare3', 'Cymatics - Snare 3.wav', 'sauce'),
  ('cymanticssnare4', 'Cymatics - Snare 4.wav', 'sauce'),
  ('cymanticssnare5', 'CCymatics - Snare 5.wav', 'sauce'),
  ('cymanticssnare6', 'Cymatics - Snare 6.wav', 'sauce'),
  ('cymanticssnare7', 'Cymatics - Snare 7.wav', 'sauce'),
  ('cymanticssnare8', 'Cymatics - Snare 8.wav', 'sauce'),
  ('cymanticssnare9', 'Cymatics - Snare 9.wav', 'sauce'),
  ('cymanticssnare10', 'Cymatics - Snare 10.wav', 'sauce'),
  ('cymanticssnare11', 'Cymatics - Snare 11.wav', 'sauce'),
  ('cymanticssnare12', 'Cymatics - Snare 12.wav', 'sauce'),
  ('cymaanticstitanvoc100', 'Cymatics - Titan Vocal Loop 8 - 100 BPM A# Min.wav', 'sauce'),
  ('cymaanticstitanvoc140', 'Cymatics - Titan Vocal Loop 25 - 140 BPM A Min.wav', 'sauce'),
  ('cymaanticstitanvoc150', 'Cymatics - Titan Vocal Loop 30 - 150 BPM C Min.wav', 'sauce'),
  ('cymaanticstitanvoc150-2', 'Cymatics - Titan Vocoder Loop 32 - 150 BPM B Min.wav', 'sauce'),
  ('cymaanticstitanvoc160', 'Cymatics - Titan Vocoder Loop 41 - 160 BPM F# Min.wav', 'sauce'),
  ('darkangel1', 'Dark Angel 001 EMaj7.wav', 'sauce'),
  ('darkangel2', 'Dark Angel 002 DMaj7.wav', 'sauce'),
  ('darkangel3', 'Dark Angel 003 CMaj7.wav', 'sauce'),
  ('darkangel4', 'Dark Angel 004 Cm7.wav', 'sauce'),
  ('darkangel5', 'Dark Angel 005 AMaj7.wav', 'sauce'),
  ('darkangel6', 'Dark Angel 006 D#Maj7.wav', 'sauce'),
  ('darkangel7', 'Dark Angel 007 DMaj7.wav', 'sauce'),
  ('envy', 'Envy 001 Cm.wav', 'sauce'),
  ('evolve', 'Evolve 001 D#6add9.wav', 'sauce'),
  ('favor', 'Favor 001 A#min7.wav', 'sauce'),
  ('gambino', 'Gambino 001 GMaj9.wav', 'sauce'),
  ('hypothesis', 'Hypothesis 001 GMaj9.wav', 'sauce'),
  ('interface', 'Interface 001 GMaj7.wav', 'sauce'),
  ('july', 'July 001 G#Maj7.wav', 'sauce'),
  ('life', 'Life 001 C6add9.wav', 'sauce'),
  ('oldtape1', 'Old Tape 001 F#Maj9.wav', 'sauce'),
  ('oldtape2', 'Old Tape 002 D#Maj9.wav', 'sauce'),
  ('oldtape3', 'Old Tape 003 CMaj9.wav', 'sauce'),
  ('perfume', 'Perfume 002 Bm9.wav', 'sauce'),
  ('sandman1', 'Sandman 001 D6add9.wav', 'sauce'),
  ('sandman2', 'Sandman 002 C6add9.wav', 'sauce'),
  ('stringpad1', 'stingsForPads 1-Concert Flute Solo.mp3', 'sauce'),
  ('stringpad2', 'stingsForPads 2-Concert Flute Solo.mp3', 'sauce'),
  ('stringpad3', 'stingsForPads 3-Concert Flute Solo.mp3', 'sauce'),
  ('stringpad4', 'stingsForPads 4-Concert Flute Solo.mp3', 'sauce'),
  ('stringpad5', 'stingsForPads 5-Concert Flute Solo.mp3', 'sauce'),
  ('stringpad6', 'stingsForPads 6-Concert Flute Solo.mp3', 'sauce'),
  ('stringpad7', 'stingsForPads 7-Concert Flute Solo.mp3', 'sauce'),
  ('creator', 'The Creator 001 A#Maj7.wav', 'sauce'),
  ('thief', 'Thief 001 C#Maj9.wav', 'sauce'),
  ('vintage', 'Vintage 001 D#Maj9.wav', 'sauce'),
  ('wishing well', 'Wishing Well 001 GMaj7.wav', 'sauce');
 

 insert into soundpacks
    (soundid, packid)
VALUES
    (1, 1),
    (2, 1),
    (3, 1),
    (4, 1),
    (5, 1),
    (6, 1),
    (7, 1),
    (8, 1),
    (9, 1),
    (10, 1),
    (11, 1),
    (12, 1),
    (1, 2),
    (2, 2),
    (3, 2),
    (4, 2),
    (5, 2),
    (6, 2),
    (7, 2),
    (8, 2),
    (9, 2),
    (10, 2),
    (11, 2),
    (12, 2)

insert into users
    (name, phone_number, hash)
values
    ('cfayard', '7066692077', '$2a$10$Dt/6Zyd1cV7I8zhL3xAKReFv1Cl6HVwT42BKEQ0P2Qmnv4.WoajBy'),
    ('nedim', '7066692044', '$2a$10$cQyIxo7pOZlPdm9fUEz0pOvr8SudfcbfU9Do/PXIhND17RfjRgdUu');



    

-- insert into usersSavedData
--     (name, screenData, dateSaved)
-- values
--     ('casey', 'fayardcasey@gmail.com', '2020-01-16'),
--     ('nedim', '123@gmail.com', '2020-01-16'),
--     ('tarik', 'abc@gmail.com', '2020-01-16'),
--     ('jb', 'jb@gmail.com','2020-01-16');

